### ISSUE TITLE
[question] Node processing time discarding "self.push" ?

### ISSUE THREAD

**Issue by fabito** [robdmc/consecution#3]
Hi @robdmc ,

Is there a known strategy for collecting node's start and end times ?
I tried the approach below but the measured time includes the subsequent nodes processing time.

```python
class BaseNode(Node):
    """Base Node for centralized instrumentation"""
    __metaclass__ = ABCMeta

    def __init__(self, name, **kwargs):
        super(BaseNode, self ).__init__(name, **kwargs)

    def process(self, item):
        try:
            self.clock.start(item.id)
            self.do_process(item)
        finally:
            self.clock.stop(item.id)

    @abstractmethod
    def do_process(self, item):
        pass
```

Ideas ? Suggestions ?

**Comment by robdmc** [comment]
Hi.

Yea, this can be tricky to get right.  Every time you call `.push(item)` you will be calling all downstream nodes.  That means you need to stop the clock around the `.push()` method.  Something like this should work.

```python
class BaseNode(Node):
    def process(self, item):
        self.clock.start(item.id)
        thing_to_push = self.do_process(item)
        self.clock.stop(item.id)
        self.push(thing_to_push)
        
        # you may or may not want to restart the clock depending on what it is you want to time
        self.clock.start(item.id)

**Comment by robdmc** [comment]
@fabito  Were you able to get that to work?  I'm going to close this issue, but feel free to reopen if you are still having issues.

**Comment by fabito** [comment]
Thanks! It worked.
